name: Update Test Badge

on:
  workflow_run:
    workflows: ["BDD Tests"]
    types:
      - completed

jobs:
  badge:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    
    steps:
    - name: Update Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GITHUB_TOKEN }}
        gistID: ${{ secrets.BADGE_GIST_ID }}
        filename: kolaba-tests.json
        label: Tests
        message: ${{ github.event.workflow_run.conclusion == 'success' && 'passing' || 'failing' }}
        color: ${{ github.event.workflow_run.conclusion == 'success' && 'brightgreen' || 'red' }}
